# action.yml
name: "Lazy Action Dotnet"
description: "Github action to perform build, test , scan and generate image."
inputs:
  src_file_dir_path:
    description: "Directory path to the solution file"
    required: true
    default: "."
  dockerfile_dir_path:
    description: "Directory path to the dockerfile"
    required: true
  ecr_repository:
    description: "Ecr repository name"
    required: true
  sonar_scan_in_docker:
    description: "Is sonar scan running as part of Dockerfile?"
    required: false
    default: "false"
  sonar_scan_in_docker_target:
    description: "sonar scan in docker target"
    required: false
    default: "sonarscan-env"
  nuget_push_enabled:
    description: "Enabled Nuget Push to Package Registry."
    required: false
    default: "false"
  container_push_enabled:
    description: "Enable Build and Push Container Image"
    required: false
    default: "true"
  nuget_pull_token:
    description: "GitHub token with repo read permissions for pulling NuGet packages"
    required: true
  nuget_push_token:
    description: "GitHub token with package write permissions for pushing NuGet packages"
    required: false

runs:
  using: "docker"
  image: docker://public.ecr.aws/p4v7w0a5/lazy/dotnet-action:sha-e6807a4faf3fc3d3ca39b3c5ca441d66d075e5fd
  env:
    GITHUB_TOKEN: ${{ inputs.nuget_pull_token }}
